# Postgres version 9.x
#   gem install pg
#
#   Ensure the Postgresql 3 gem is defined in your Gemfile
#   gem 'pg'
development:
  adapter: postgresql
  encoding: unicode
  database: userbase_development
  pool: 5
  username: postgres
  password: tried coal blew slightly
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  password: 
production:
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  pool: 5
  password: 
